### ISSUE TITLE
pypi package?

### ISSUE THREAD

**Issue by turian** [PyTorchLightning/lightning_sphinx_theme#15]
Do you mind pushing a pypi release of this theme? We are using it but cannot have git URLs in packages that we push to pypi. Thus, we would love a pypi version of this theme.

**Comment by turian** [comment]
The alternative would be that I fork the repo and create a pypi package myself (I would avoid name-squatting of course) but I would prefer just to pin to an officially released package. Thank you for the wonderful theme

**Comment by Borda** [comment]
@turian good suggestion, I would recommend to open this question on the upstream repo as this is also "just a fork"
see: https://github.com/pytorch/pytorch_sphinx_theme

**Comment by Borda** [comment]
Anyway, not sure why this template shall be part of any pypi requirements, mind share your repo?

**Comment by turian** [comment]
@Borda I need it as a pypi package because I want to include this package in my setup.py

https://github.com/torchsynth/torchsynth

**Comment by Borda** [comment]
> I need it as a pypi package because I want to include this package in my setup.py

I see it is just for convenience, but in fact, it does not affect any of your functionality, as you can keep the HTTP simply here
https://github.com/torchsynth/torchsynth/blob/main/docs/requirements.txt as 
```
-r ../requirements.txt
https://github.com/PyTorchLightning/lightning_sphinx_theme/tarball/master#egg=pt-lightning-sphinx-theme
sphinxcontrib-napoleon
sphinx-autodoc-typehints
sphinx_rtd_theme
myst-parser
```

**Comment by ethanwharris** [comment]
@Borda No, I think the current system is best. Having it as a package would also mean that we would have to release new versions every time we make a change, would be a bit annoying haha
